name: App Shortcut Request
description: Reqeuest a new app shortcut
title: "[New App Shortcut]: "
labels: ["New App Shortcut", "enhancement"]
assignees:
  - PRProd
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to contribute to this project with your requests!
  - type: input
    id: appname
    attributes:
      label: App Name
      description: The name of the app you'd like to see added
      placeholder: ex. YouTube
    validations:
      required: true
  - type: dropdown
    id: platform
    attributes:
      label: Device Platform
      options: 
       - Amazon Fire
       - Apple TV
       - Chromecast
       - NVIDIA Shield
       - Xiaomi
      multiple: true
      description: The kind of device you own.  You can choose one or more from this list.
    validations:
      required: true
  - type: input
    id: appstoreLink
    attributes:
      label: App Store Link and/or URL to .apk file if sideloaded
      description: Optionally provide a link to the Google Play or Apple store where this app can be downloaded.  If this is a sideloaded app, please include a full URL for where the .apk can be found
    validations:
      required: false
  - type: textarea
    id: detailedAppInfo
    attributes:
      label: Application Info
      description: Optional, but EXTREMELY helpful.  Follow the instructions [listed here](https://github.com/PRProd/HA-Firemote/wiki/How-Can-I-Help%3F#details-for-app-requests) and paste the results.
      placeholder: 
    validations:
      required: false
  - type: textarea
    id: additionalInfo
    attributes:
      label: Optional Comments
      description: Add any additional related comments here, or maybe write something clever like a poem or a joke.
      placeholder: 
    validations:
      required: false
