name: App Shortcut Request
description: Reqeuest a new app shortcut
title: "[New App Shortcut]: "
labels: ["New App Shortcut", "enhancement"]
assignees:
  - PRProd
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to contribute to this project with your requests!
  - type: input
    id: appname
    attributes:
      label: App Name
      description: The name of the app you'd like to see added
      placeholder: ex. YouTube
    validations:
      required: true
  - type: input
    id: platform
    attributes:
      label: Device Platform
      description: The kind of device you own.  This has to be either "Amazon Fire", "NVIDIA Shield", or both.
      placeholder: ex. both
    validations:
      required: true
  - type: checkboxes
    id: canBeDownloaded
    attributes:
      label: Is this app downloadable through you device's "store" app?
      description: This answer must be yes.  If the app is not available to download through the native download store, then it is potentially unsafe and will not be considered for app shortcuts.  All "sideloaded" app requests will be rejected for now.
      options:
        - label: 'Yes'
          required: true
  - type: textarea
    id: additionalInfo
    attributes:
      label: Optional Comments
      description: Add any other related comments here, or leave this blank.  [Specifically, these helpful steps will likely get your request processed faster](https://github.com/PRProd/HA-Firemote/wiki/How-Can-I-Help%3F#details-for-app-requests)
      placeholder: 
    validations:
      required: false
