name: Language Support
description: "Request support for any currently unsupported language"
title: "[New Language Support]: "
labels: ["Region Issue", "enhancement"]
assignees:
  - PRProd
body:
  - type: markdown
    attributes:
      value: "Thank you for taking the time to contribute to this project!  Please use this issue form to request new language support for any currently unsupported language.  [Click here](https://github.com/PRProd/HA-Firemote/wiki/#which-languages-are-currently-supported) to view the currently supported languages.<br><br>"
  - type: input
    id: langcode
    attributes:
      label: Language Code
      description: "The official 2 letter language code.  Code lookup can be found here: https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes"
      placeholder: "example: en"
    validations:
      required: true
  - type: markdown
    attributes:
      value: "<br><br>For Apple TV Users: Follow the instructions [listed here](https://github.com/PRProd/HA-Firemote/wiki/Providing-Details-for-App-Launcher-Requests#for-apple-tv-devices)."
  - type: textarea
    id: appleTVSourceList
    attributes:
      label: Apple TV source_list
      placeholder: 
      render: text
    validations:
      required: false
  - type: markdown
    attributes:
      value: <br>
  - type: textarea
    id: wordPhraseMap
    attributes:
      label: Translation Chart
      description: 'To the best of your ability, Please write the best translation for each of the items listed here'
      render: text
      value: |
         1. App Launch Button => 
         2. App Launcher Relative Scale =>
         3. Apple Computers => 
         4. Apple Music => 
         5. Apple Photos => 
         6. Associated => 
         7. bottom => 
         8. Compatibility Mode => 
         9. Computers => 
        10. Device Family => 
        11. Device Model => 
        12. Device Name Text Color => 
        13. Function: Control Center => 
        14. Function: Find My Remote => 
        15. Function: Mute => 
        16. Function: Next => 
        17. Function: Previous => 
        18. Function: Reboot => 
        19. Function: Search => 
        20. Function: Settings => 
        21. Function: Skip Backward => 
        22. Function: Skip Forward => 
        23. Function: Switch Apps => 
        24. hidden => 
        25. Music => 
        26. Name Position => 
        27. Optional => 
        28. Photos => 
        29. Remote Style => 
        30. Scale => 
        31. Settings => 
        32. Search => 
        33. top => 
        34. Visible Device Name =>
    validations:
      required: true
  - type: markdown
    attributes:
      value: <br>
  - type: textarea
    id: additionalInfo
    attributes:
      label: Additional Comments (optional)
      placeholder: 
    validations:
      required: false
