name: Language Support
description: "Request support for any currently unsupported language"
title: "[New Language Support]: "
labels: ["Region Issue", "enhancement"]
assignees:
  - PRProd
body:
  - type: markdown
    attributes:
      value: "Thank you for taking the time to contribute to this project!  Please use this issue form to request new language support for any currently unsupported language.  [Click here](https://github.com/PRProd/HA-Firemote/wiki/#which-languages-are-currently-supported) to view the currently supported languages.<br><br>"
  - type: input
    id: langcode
    attributes:
      label: Language Code
      description: "The official 2 letter language code.  Code lookup can be found here: https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes"
      placeholder: "example: en"
    validations:
      required: true
  - type: markdown
    attributes:
      value: "<br><br>For Apple TV Users: Follow the instructions [listed here](https://github.com/PRProd/HA-Firemote/wiki/Providing-Details-for-App-Launcher-Requests#for-apple-tv-devices)."
  - type: textarea
    id: appleTVSourceList
    attributes:
      label: Apple TV source_list
      placeholder: 
      render: text
    validations:
      required: false
  - type: markdown
    attributes:
      value: <br>
  - type: textarea
    id: wordPhraseMap
    attributes:
      label: 'Translation Chart'
      description: 'To the best of your ability, Please write the best translation for each of the items listed here'
      render: text
      value: |
        01. App Launch Button => 
        02. App Launcher Relative Scale =>
        03. Apple Computers => 
        04. Apple Music => 
        05. Apple Photos => 
        06. Associated => 
        07. bottom => 
        08. Compatibility Mode => 
        09. Computers => 
        10. Default for => 
        11. Device Family => 
        12. Device Model => 
        13. Device Name Text Color => 
        14. Entity => 
        15. Function: Channel + => 
        16. Function: Channel - => 
        17. Function: Control Center => 
        18. Function: Find My Remote => 
        19. Function: Mute => 
        20. Function: Next => 
        21. Function: Previous => 
        22. Function: Reboot => 
        23. Function: Search => 
        24. Function: Settings => 
        25. Function: Skip Backward => 
        26. Function: Skip Forward => 
        27. Function: Switch Apps => 
        28. Function: Volume + => 
        29. Function: Volume - => 
        30. hidden => 
        31. Music => 
        32. Name Position => 
        33. optional => 
        34. Photos => 
        35. Remote Style => 
        36. Scale => 
        37. Settings => 
        38. Search => 
        39. top => 
        40. Visible Device Name =>
    validations:
      required: true
  - type: markdown
    attributes:
      value: <br>
  - type: textarea
    id: additionalInfo
    attributes:
      label: Additional Comments (optional)
      placeholder: 
    validations:
      required: false
